name: execute_bot2
description: Bot 2 - Reconciliación Softland vs Cartola (TEST)

flow:
  entrypoint: bot2_executor:execute_bot2

deployments:
  - name: bot2-test
    description: Bot 2 - Reconciliación Softland vs Cartola (TEST)
    entrypoint: bot2_executor:execute_bot2
    tags:
      - bot2
      - reconciliacion
      - test
    parameters:
      fecha_prueba: null
    schedules: []
    work_queue: default